# Generated by Django 5.0 on 2024-05-13 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnergyConsumption',
            fields=[
                ('consumption_id', models.AutoField(primary_key=True, serialize=False)),
                ('active_power', models.FloatField()),
                ('time', models.FloatField()),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='smartwatt.user')),
            ],
        ),
    ]
