# Generated by Django 5.0 on 2024-09-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartwatt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energydata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
