# Generated by Django 5.0 on 2024-09-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartwatt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
