# Generated by Django 5.0 on 2024-08-22 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartwatt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
    ]
