# Generated by Django 5.0 on 2024-12-04 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartwatt', '0002_contactmessage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='user',
        ),
    ]
