# Generated by Django 5.0 on 2024-11-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartwatt', '0002_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(choices=[('Sahiwal', 'Sahiwal'), ('Lahore', 'Lahore'), ('Islamabad', 'Islamabad')], default='Sahiwal', max_length=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.CharField(default='Farid Town', max_length=50),
        ),
    ]
