# Generated by Django 5.0 on 2024-12-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartwatt', '0003_remove_contactmessage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(choices=[('Sahiwal', 'Sahiwal'), ('Lahore', 'Lahore'), ('Islamabad', 'Islamabad'), ('Karachi', 'Karachi'), ('Rawalpindi', 'Rawalpindi'), ('Faisalabad', 'Faisalabad'), ('Multan', 'Multan'), ('Peshawar', 'Peshawar'), ('Quetta', 'Quetta'), ('Gujranwala', 'Gujranwala'), ('Sialkot', 'Sialkot'), ('Mardan', 'Mardan'), ('Bahawalpur', 'Bahawalpur'), ('Murree', 'Murree'), ('Abbottabad', 'Abbottabad')], default='Sahiwal', max_length=15),
        ),
    ]
